version: "3"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  boot:
    build: .
    ports:
      - 8001:8001
    depends_on:
      - postgres
      - flyway
      
  flyway:
    image: flyway/flyway:6.4.2-alpine
    command: -url=${POSTGRES_URL:-} -user=${POSTGRES_USER:-} -password=${POSTGRES_PASSWORD:-} -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
      
volumes:
  postgres-data:
    driver: local